### ISSUE TITLE
Docker Images not synced

### ISSUE THREAD

**Issue by mysticaltech** [MontFerret/worker#14]
Hello, first of all, thank you for this amazing project. You really have a vision behind this and it's looking to be awesome! About this issue, it's just that the container won't start, the entrypoint or init string is not found I would guess.  But when built locally, all good, so not an urgent issue for me.

**Comment by ziflex** [comment]
Hi, thanks for your kind words and the heads up! I will look into this.

**Comment by ziflex** [comment]
Fixed. Could you pull the latest and verify?

**Comment by mysticaltech** [comment]
Working like a charm, thank you! 🙏🏻
