### ISSUE TITLE
How I can to execute script with about:blank

### ISSUE THREAD

**Issue by Hedgehogues** [MontFerret/worker#7]
I want to execute script like [this](https://github.com/MontFerret/ferret/blob/e8d82d93964e7e550bb1ed431a7e41cc8e9cfa21/examples/blank-page.fql). I want to pass page text to ferret

**Comment by Hedgehogues** [comment]
Why you remove [this](https://github.com/MontFerret/ferret/issues/385) feature? I want to use for working with html in offline

**Comment by Hedgehogues** [comment]
I was found 0.10.0 release and I found this [PR](https://github.com/MontFerret/ferret/pull/434/files). I take next request:

![image](https://user-images.githubusercontent.com/4973667/83175642-def95c00-a124-11ea-9b34-0d8d79d287b3.png)

```
{
    "error": "code=400, message=Syntax error: offset=13, error=invalid character '\\n' in string literal, internal=invalid character '\\n' in string literal"
}
```

**Comment by ziflex** [comment]
> Why you remove [this](https://github.com/MontFerret/ferret/issues/385) feature? I want to use for working with html in offline
It's not removed, just renamed to ``PARSE``.

**Comment by ziflex** [comment]
> I was found 0.10.0 release and I found this [PR](https://github.com/MontFerret/ferret/pull/434/files). I take next request:
> 
> ![image](https://user-images.githubusercontent.com/4973667/83175642-def95c00-a124-11ea-9b34-0d8d79d287b3.png)
> 
> ```
> {
>     "error": "code=400, message=Syntax error: offset=13, error=invalid character '\\n' in string literal, internal=invalid character '\\n' in string literal"
> }
> ```

JSON does not support multi-line strings. You need to convert it into a single string keeping new line breaks. (``\n`` )

**Comment by Hedgehogues** [comment]
![image](https://user-images.githubusercontent.com/4973667/83188790-e32f7480-a138-11ea-92f9-3297ebb7c2cf.png)
What about this? Not found function `EXPECT`

**Comment by Hedgehogues** [comment]
What mean `EXPECT` in test of PR? Is this mock function?

**Comment by ziflex** [comment]
``EXPECT`` is a part of end-to-end testing and not available in the final version of Ferret.
Why are you using it?

**Comment by Hedgehogues** [comment]
I want to use offline html data. I pass into request html data. I want to add a prerocessing before parsing. For example, I want to add retry or process status codes or another features.

**Comment by Hedgehogues** [comment]
My simple architecture 
![image](https://user-images.githubusercontent.com/4973667/83193573-f2fe8700-a13f-11ea-9bb1-f1977383d427.png)

I have the only golang-service. Therefore I want to use your docker-container without implementation of service

**Comment by ziflex** [comment]
Sorry, I meant why you are using ``EXPECT`` function.
Just remove the function and the query should work.

**Comment by Hedgehogues** [comment]
Of, course, I try it. I have next problem:

![image](https://user-images.githubusercontent.com/4973667/83194245-02ca9b00-a141-11ea-88aa-5a611d980b67.png)

**Comment by ziflex** [comment]
Could you post the request body here as text?

**Comment by Hedgehogues** [comment]
```
{
	"text": "LET page = PARSE(@text, {    driver: 'cdp'}) \n LET title = ELEMENT(page, 'title') \n  RETURN {x: title.innerText}",	
	"params": {
		"text": "<!DOCTYPE html>\n<html lang=\"en\"> \n<head>\n    <meta charset=\"UTF-8\">\n    <title>Offline</title>\n</head>\n<body>\n    <h1>Hello world</h1>\n</body>\n</html>"
	}
}
```

**Comment by Hedgehogues** [comment]
This problem with chrome driver, I think. I don't use them. Or this one required? But for why? I don't want to use driver and I want to use native way.

**Comment by ziflex** [comment]
If you don't need a CDP driver, then just use ``LET page = PARSE(@text)``.
Regarding the error: I assume you are not using the worker via Docker, are you? If so, it's failing because cannot connect to Chromium/Chrome.

**Comment by Hedgehogues** [comment]
I don't. I think, I solve it, when I commet the chromium in code while in debugging. Running in docker to help me. Thanks a lot!
