### ISSUE TITLE
feat(api): return Server IP

### ISSUE THREAD

**Issue by PierreBrisorgueil** [MontFerret/worker#8]
Hello, it might be interesting to return the execution ip of the request for tracking / debugging on regular scraps.

This can allow you to be aware of spam from an IP address, to understand if it is banned etc ...

**Comment by ziflex** [comment]
You mean correlation id?

**Comment by PierreBrisorgueil** [comment]
@ziflex hello,
No, but that could be interesting too. 

I am really thinking of the public IP adress which could end up in a fail2ban or other, due to poor management of docker API for example, it can be interesting then to understand that this only blocks on a specific IP / environment. 

But it may be too specific to a usecase use of x instances.
